In [1]:
import pandas as pd
import numpy as np

In [2]:
credits = pd.read_csv("tmdb_5000_credits.csv")
movies = pd.read_csv("tmdb_5000_movies.csv")

In [3]:
movies.head(1)

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                      homepage     id  \
0  http://www.avatarmovie.com/  19995   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   

  original_title                                           overview  \
0         Avatar  In the 22nd century, a paraplegic Marine is di...   

   popularity                               production_companies  \
0  150.437577  [{"name": "Ingenious Film Partners", "id": 289...   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   

                       tagline   title  vote_average  vote_count  
0  Enter the World of Pandora.  Avatar           7.2       11800

In [4]:
credits.head(1)

movie_id   title                                               cast  \
0     19995  Avatar  [{"cast_id": 242, "character": "Jake Sully", "...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...

In [5]:
credits.head(1)['cast']

0    [{"cast_id": 242, "character": "Jake Sully", "...
Name: cast, dtype: object

In [6]:
movies = movies.merge(credits,on='title')   # Dono data ko marge karo

In [7]:
movies = movies[['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew']]   #Baki feture remoed krna 

In [8]:
movies.head(1)

movie_id   title                                           overview  \
0     19995  Avatar  In the 22nd century, a paraplegic Marine is di...   

                                              genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                            keywords  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...

In [9]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [10]:
import ast

def convert(obj):
    L = []                                         # Ek khali list banate hain, jisme hum 'name' values store karenge.
    for i in ast.literal_eval(obj):                             # String ko Python list mein convert karega ast or har dictionary par loop chalate hain.
        L.append(i['name'])                              # Har dictionary ke 'name' value ko list mein add karte hain.
    return L

In [11]:
movies['genres'] = movies['genres'].apply(convert)
movies['keywords'] = movies['keywords'].apply(convert)

In [12]:
movies.iloc[0].genres 

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [13]:
# movies['cast'][0]  # Hume sirf isme se name chahiye wo bhi real

In [14]:
import ast

def convert3(obj):
    L = []                            # Khali list banate hain 'name' values store karne ke liye.
    counter = 0                                                 # Counter ka initial value 0 set karte hain.
    for i in ast.literal_eval(obj):                       # Stringified list ko Python list mein convert karte hain aur uspar loop chalate hain.
        if counter != 3:                                           # Agar counter 3 se chhota hai tabhi 'name' values ko process karein.
            L.append(i['name'])                      # Current dictionary ka 'name' key extract karke list L mein add karte hain.
            counter += 1                   # Counter ko 1 se increment karte hain.
        else:  
            break                # Agar counter 3 ho gaya, loop ko rok dete hain.
    
    return L  # Final list return karte hain.


In [15]:
movies['cast'] = movies['cast'].apply(convert3)

In [16]:
def fetch_director(obj):
    L = []         
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':  #ye sirf job ke ander ke director ke name ko hi fatch krege                                               .
            L.append(i['name'])
            break
    return L
    

In [17]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [18]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [19]:
# Ye code overview column ki har string ko split karke list banayega, aur non-string ya NaN values ke liye empty list [] return karega

movies['overview'].apply(lambda x: x.split() if isinstance(x, str) else [])

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bond’s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...                        
4804    [El, Mariachi, just, wants, to, play, his, gui...
4805    [A, newlywed, couple's, honeymoon, is, upended...
4806    ["Signed,, Sealed,, Delivered", introduces, a,...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Ever, since, the, second, grade, when, he, fi...
Name: overview, Length: 4809, dtype: object

In [20]:
movies['overview'] = movies['overview'].apply(lambda x: x.split() if isinstance(x, str) else [])  #  yha save kiya he

In [21]:
# column ke names ka space remove kre 

In [22]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ", "") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ", "") for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ", "") for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ", "") for i in x])

In [23]:
# ab hum    overview, genres, keywords, cast, crew   column ko  movies['tags'] column me  ADD kr lege  or phir in  column ko delete kr dege				

In [24]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [25]:
movies.head(1)

movie_id   title                                           overview  \
0     19995  Avatar  [In, the, 22nd, century,, a, paraplegic, Marin...   

                                         genres  \
0  [Action, Adventure, Fantasy, ScienceFiction]   

                                            keywords  \
0  [cultureclash, future, spacewar, spacecolony, ...   

                                            cast            crew  \
0  [SamWorthington, ZoeSaldana, SigourneyWeaver]  [JamesCameron]   

                                                tags  
0  [In, the, 22nd, century,, a, paraplegic, Marin...

In [26]:
new_df = movies[['movie_id','title', 'tags']]
new_df.head(2)

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   

                                                tags  
0  [In, the, 22nd, century,, a, paraplegic, Marin...  
1  [Captain, Barbossa,, long, believed, to, be, d...

In [27]:
# ab tags colum ki list ko string me convert krte he

In [28]:
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

C:\Users\AFNANKHAN\AppData\Local\Temp\ipykernel_8108\1824047427.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))


In [29]:
new_df['tags'][0]    # yha list se string me convert ho gya he 

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [30]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())   # ye lower case me convert kr dega tegs column ke data ko

C:\Users\AFNANKHAN\AppData\Local\Temp\ipykernel_8108\3764229856.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())   # ye lower case me convert kr dega tegs column ke data ko


In [31]:
new_df.head(2)

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   

                                                tags  
0  in the 22nd century, a paraplegic marine is di...  
1  captain barbossa, long believed to be dead, ha...

In [32]:
import nltk
from nltk.stem.porter import PorterStemmer

Ps = PorterStemmer()

def stem(text):
    y = []
    for i in text.split():  # Colon (:) add kiya
        y.append(Ps.stem(i))  # Stemmed word ko list me add kiya
    return " ".join(y)  # List ko string me convert kiya


In [33]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\AFNANKHAN\AppData\Local\Temp\ipykernel_8108\3213734980.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)


In [34]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=5000, stop_words='english')
vector = cv. fit_transform(new_df['tags']).toarray ()


In [35]:
vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [36]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [37]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vector)



In [38]:
similarity[0]              #pehli movie 1 similer he 

array([1.        , 0.08346223, 0.0860309 , ..., 0.04499213, 0.        ,
       0.        ])

In [39]:
similarity[1]                   # dusri me bhi 1 he yani smiler he  

array([0.08346223, 1.        , 0.06063391, ..., 0.02378257, 0.        ,
       0.02615329])

In [40]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(1214, 0.28676966733820225),
 (2405, 0.26901379342448517),
 (3729, 0.2605130246476754),
 (507, 0.255608593705383),
 (539, 0.25038669783359574)]

In [41]:
def recomended(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]  # Correctly fetch the distances for the given movie
    movie_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:6]  # Fix: Use 'distances' instead of 'CS[0]'

    for i in movie_list:
        print(new_df.iloc[i[0]].title)


In [42]:
recomended('Batman Begins')

The Dark Knight
Batman
Batman
The Dark Knight Rises
10th & Wolf


In [43]:
import pickle

pickle.dump(new_df,open('movies.pkl', 'wb'))

In [44]:
pickle.dump(new_df.to_dict(),open('movie_dict.pkl', 'wb'))

In [45]:
pickle.dump(similarity,open('similarity.pkl', 'wb'))